### ISSUE TITLE
Username in list of mentioned User.txt file.

### ISSUE THREAD

**Issue by nl1213** [Fitzy1293/reddit#2]
My Username was put in the user.txt file and it says on your front page that "user.txt is good if you are looking for users to analyze". Is there any way to get my username off of that list. I would rather not draw attention to my account and I did not want my account to be part of any analysis.

**Comment by Fitzy1293** [comment]
@nl1213 
I will certainly remove you from this list. I am sorry that I did not see this earlier because I've been busy with school and haven't kept up with this project.
The program that creates users.txt uses a list of subreddits and gets people who have posted in those subreddits. I just used the top subreddits and got people who posted to those. I figured the aggregate of users in the list would be representative of reddit's average userbase at that time. I know it must be weird showing up on a list from a random program, but there was no ill intent behind it. 

Edit: I assumed nl1213 was your reddit username, I guess it's not because that's not in users.txt. Just message my reddit u/crazed404 and I'll delete it (I'm assuming you don't want to post it in this issue thread, and github doesn't seem to have a DM feature).

**Comment by ghost** [comment]
Ron, Owen or whatever... can you kindly do the same thing and remove the user mucho_gris from your users data list? Thank you in advance.

**Comment by Fitzy1293** [comment]
@muchogrrris done

**Comment by Fitzy1293** [comment]
Users deleted from list.
